### ISSUE TITLE
Why the link stats page has to be public?

### ISSUE THREAD

**Issue by BenYangOvO** [SachinSAgrawal/YOURLS-Device-Details#1]
Just wanted to prevent access log data from being scanned by random cyber attackers, and out of some concern on privacy and my curious.

**Comment by SachinSAgrawal** [comment]
It doesn't have to be if you want to install this plugin on a private instance, but if you want to mimic something like Grabify, I would recommend making the stats page public. Having the stats page public with or without this plugin is still a security vulnerability, so it really depends on how much risk you want to take. I hope that answers your question.
